### ISSUE TITLE
@HasOne(Pet)

### ISSUE THREAD

**Issue by pleerock** [ubiquits/quickstart#18]
One thing I noticed when browsing this repository:

```typescript
  @HasOne(Pet)
```
As I understood this is decorator of `@OneToOne`. So, what I want to say is that you'll be in trouble if you'll have a reference from inverse side (from Pet). To resolve this problem the only solution is to pass a Pet in a function, like this: `@HasOne(() => Pet)`

**Comment by zakhenry** [comment]
I don't follow - why would that cause a problem? Something about circular module resolution?

**Comment by zakhenry** [comment]
Note that I haven't completed all the decorators yet, in this case the inverse side will be a decorator like `@BelongsTo(User, 'pet')`.

**Comment by pleerock** [comment]
You'll have problems such relation:
```typescript
User {
 @HasOne(Pet)
pet: Pet;
}
Pet {
 @BelongsTo(User, "pet")
user: User;
}
```
yes, its about a circular module resolution.

**Comment by pleerock** [comment]
btw angular resolves this problem using `fowardRef` function

**Comment by zakhenry** [comment]
Hmm interesting, thanks for the issue. I wonder if I can fix the issue not allowing passing of class, and just use metadata reflection. Something to ponder...

**Comment by pleerock** [comment]
metadata reflect will not help. It was the first think I tried. same issue. btw here is [issue in typescript repo](https://github.com/Microsoft/TypeScript/issues/4521)

**Comment by zakhenry** [comment]
Ok now I see your note in typeorm:
> we are forced to use a function that returns a class, instead of using class directly, because of the language specifics. We can also write it as a () => Photo, but we use type => Photo as convention to increase code readability a bit. type variable itself does not contain anything.

Missed that, oops

**Comment by zakhenry** [comment]
Closed in https://github.com/ubiquits/ubiquits/pull/123
